### PR TITLE
add links instead of projects

### PR DESCRIPTION
**Pull request by obeid**
- place links with images to other related websites instead of projects
- kill unused demo images
- remove that glitter effect on background images

### CODE REVIEW

**Comment by nmashton** [comment]
This is awesome, but I have one suggestion!

Monthly Review and Socialist Worker are both great, but they're not particularly closely aligned with DSA. The latter is the [ISO](http://www.internationalsocialist.org/)'s publication, and the former is old-school orthodox Marxist in a way that not too many DSAers are.

Y'know, if I had to pick one other organization's magazine and one publication representing a strand of Marxism that's not especially dominant in DSA, I'd go with Solidarity's [Against the Current](https://www.solidarity-us.org/atc) and [Viewpoint](http://viewpointmag.com/), respectively. :)

Anyway, [In These Times](http://inthesetimes.com/) and [New Politics](http://newpol.org/) both have more of a history of DSA involvement and are good publications, so they may be good replacements.

**Comment by nmashton** [comment]
Incidentally, Soli's website could really use a design reboot, huh?

**Comment by obeid** [comment]
Thanks so much for this comment. This is exactly the stuff that I need a more experienced person in this space to look at. I will add all four you suggested and remove MR and SW. 

Let's have our people talk to Soli's people.

**Comment by nmashton** [comment]
Hmm, I didn't mean to actually *suggest* Soli's publication and Viewpoint, but you now what? Go for it. :)

:shipit:

**Pull request merged**
